---
- name: 修改主机名
  hostname:
    name: "{{ hostvars[inventory_hostname].node_domain }}"

- name: 添加hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: 拷贝时区
  copy:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
    backup: yes

- name: 确保配置文件存在
  file:
    path: "{{ sysctl_file }}"
    state: touch

- name: 启动 br_netfilter 内核模块
  command:
    cmd: modprobe br_netfilter

- name: 配置Containerd所需的内核
  lineinfile:
    path: "{{ sysctl_file }}"
    line: "{{ item }}"
    state: present
  loop: "{{ sysctl_params }}"

- name: 应用 sysctl 参数
  command: sysctl -p "{{ sysctl_file }}"

- name: 关闭 swap
  command: swapoff -a

- name: 注释掉 fstab 中的 swap 行
  lineinfile:
    path: /etc/fstab
    regexp: '^(.*swap.*)'
    state: absent

- name: 加载 ipvs 模块
  shell: |
    if [ -d /usr/lib/modules/$(uname -r)/kernel/net/netfilter/ipvs/ ]; then
        for module in $(ls /usr/lib/modules/$(uname -r)/kernel/net/netfilter/ipvs/); do
            module=${module%%.*}
            modprobe $module >/dev/null 2>&1
        done
    fi
  args:
    executable: /bin/bash
  when: PROXY_MODE == "ipvs"

# 针对不同操作系统（CentOS vs Ubuntu）安装依赖包
- name: 安装依赖包
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "ipset"
    - "chrony"
    - "ntpdate"
    - "{{ 'iptables' if ansible_facts['distribution'] == 'CentOS' else 'iptables-persistent' }}"

- name: 启动防火墙
  systemd:
    name: "{{ 'iptables' if ansible_facts['distribution'] == 'CentOS' else 'netfilter-persistent' }}"
    state: started
    enabled: yes

- name: 配置Chrony NTP服务器
  template:
    src: server-chrony.conf.j2
    dest: "{{ chrony_config_file }}"
  when: ntp_server | default(false)
  vars:
    chrony_config_file: "{{ '/etc/chrony.conf' if ansible_facts['distribution'] == 'CentOS' else '/etc/chrony/chrony.conf' }}"

- name: 配置Chrony NTP客户端
  template:
    src: client-chrony.conf.j2
    dest: "{{ chrony_config_file }}"
  when: ntp_server | default(false) != "true"
  vars:
    chrony_config_file: "{{ '/etc/chrony.conf' if ansible_facts['distribution'] == 'CentOS' else '/etc/chrony/chrony.conf' }}"

- name: 定义NTP服务器地址
  set_fact:
    ntp_server: "{{ (groups['all'] | selectattr('ntp_server', 'defined') | selectattr('ntp_server') | list | first) if (groups['all'] | selectattr('ntp_server', 'defined') | selectattr('ntp_server') | list | length) > 0 else 'ntp.aliyun.com' }}"

- name: 启动NTP服务
  systemd:
    name: chronyd.service
    state: started
    enabled: yes

- name: 时间同步
  shell: "ntpdate {{ ntp_server }}"
  register: ntpdate_result
  ignore_errors: true

- name: 初始化防火墙
  shell: |
    # 检查规则是否存在，存在则删除
    iptables -t filter -C INPUT -j REJECT --reject-with icmp-host-prohibited 2>/dev/null && iptables -t filter -D INPUT -j REJECT --reject-with icmp-host-prohibited || echo "规则不存在，跳过"
    iptables -t filter -C FORWARD -j REJECT --reject-with icmp-host-prohibited 2>/dev/null && iptables -t filter -D FORWARD -j REJECT --reject-with icmp-host-prohibited || echo "规则不存在，跳过"

- name: 配置重启关机自动保存IPtables规则
  lineinfile:
    path: /etc/sysconfig/iptables-config
    regexp: '^IPTABLES_SAVE_ON_STOP="no"'
    line: 'IPTABLES_SAVE_ON_STOP="yes"'
    backrefs: yes
  when: ansible_facts['distribution'] == 'CentOS'

- name: Ubuntu上netfilter-persistent保存规则
  command: netfilter-persistent save
  when: ansible_facts['distribution'] == 'Ubuntu'

